导出到logdb时配置ip
qiniu/pandora-go-sdk pull request #185
Opened 2018-09-10 11:09 UTC by redHJ

@wonderflow 

1. 导出到logdb时配置ip
2. 如果ip有变化，需要更新export

2018-09-11 03:23 UTC, wonderflow requested changes
create的时候就创建一次就行了

2018-09-11 03:23 UTC, wonderflow commented on pipeline/api.go
> -	}
没有变化不更新的逻辑不用删掉

2018-09-11 03:23 UTC, wonderflow commented on pipeline/api.go
> +	output, err := c.GetExport(&GetExportInput{
这里为什么还要再GetExport，不看当前传进来的 `ex ExportDesc`

2018-09-11 05:55 UTC, wonderflow commented on pipeline/api.go
> +	spec := &ExportLogDBSpec{DestRepoName: repoName, Doc: docs, OmitEmpty: omitEmpty, OmitInvalid: omitInvalid, LocateIPConfig: ipConfig}
这里确实是要的，效果是新增字段的时候设置ipconfig，我怎么没有看到create export部分的代码有改动哈？

2018-09-11 09:20 UTC, redHJ commented on pipeline/api.go
> +	spec := &ExportLogDBSpec{DestRepoName: repoName, Doc: docs, OmitEmpty: omitEmpty, OmitInvalid: omitInvalid, LocateIPConfig: ipConfig}
https://github.com/qiniu/pandora-go-sdk/pull/185/files#diff-b9cbd0b1bea25ccb74c5f77d031193fbR371 这里，在spec里，spec 在CreateExport是个interface{}

2018-09-12 01:51 UTC, wonderflow approved these changes

2018-09-12 01:51 UTC, merged

2018-09-12 01:52 UTC, wonderflow commented
LGTM